force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>LINE-{0000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <label>Qty</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Tax_Inclusive_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Inclusive_Amount__c</fullName>
    <label>Tax Inclusive Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt_Line_Item__c/Sales_Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Receipt Line Item</label>
    <nameField>
        <displayFormat>SRL-{0000}</displayFormat>
        <label>Sales Receipt Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QboSalesLineItem.cls
public virtual class QboSalesLineItem {
    
    public static Sobject convert(Sales_Receipt_Line_Item__c lineItem, QboSalesLineItemDetail SalesItemLineDetail){
        
        lineItem.Tax_Inclusive_Amount__c = SalesItemLineDetail.TaxInclusiveAmt;
        lineItem.Service_Date__c = SalesItemLineDetail.ServiceDate;
        lineItem.Discount_Rate__c = SalesItemLineDetail.DiscountRate;
        lineItem.Qty__c = SalesItemLineDetail.Qty;
        lineItem.Unit_Price__c = SalesItemLineDetail.UnitPrice;
        lineItem.Discount_Amount__c = SalesItemLineDetail.DiscountAmt;
        return lineItem;
    }

    public static Sobject convert(Invoice_Line_Item__c lineItem , QboSalesLineItemDetail SalesItemLineDetail){
        
        lineItem.Tax_Inclusive_Amount__c = SalesItemLineDetail.TaxInclusiveAmt;
        lineItem.Service_Date__c = SalesItemLineDetail.ServiceDate;
        lineItem.Discount_Rate__c = SalesItemLineDetail.DiscountRate;
        lineItem.Qty__c = SalesItemLineDetail.Qty;
        lineItem.Unit_Price__c = SalesItemLineDetail.UnitPrice;
        lineItem.Discount_Amount__c = SalesItemLineDetail.DiscountAmt;
        return lineItem;
    }

 
 
     



}