force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>LINE-{0000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <label>Qty</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt_Line_Item__c/Sales_Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Receipt Line Item</label>
    <nameField>
        <displayFormat>SRL-{0000}</displayFormat>
        <label>Sales Receipt Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Receipt_Line_Item__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QboGroupLineItem.cls
public virtual class QboGroupLineItem {
        
    // sets values peculiar to the group line item        
    public static Sobject convert(Sales_Receipt_Line_Item__c lineItem , QboGroupLineItemDetail GroupLineDetail ){
        lineItem.Qty__c = GroupLineDetail.Quantity;
        if(GroupLineDetail.Line != null && GroupLineDetail.Line.size()>0){
            lineItem.Line__c = String.join(GroupLineDetail.Line, '\n');
        }
        return lineItem;
    }
        
    public static Sobject convert(Invoice_Line_Item__c lineItem , QboGroupLineItemDetail GroupLineDetail){
        lineItem.Qty__c = GroupLineDetail.Quantity;
        if(GroupLineDetail.Line != null && GroupLineDetail.Line.size()>0){
            lineItem.Line__c = String.join(GroupLineDetail.Line, '\n');
        }
        return lineItem;
    }
    

}