force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>LINE-{0000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Receipt_Line_Item__c/Sales_Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Receipt Line Item</label>
    <nameField>
        <displayFormat>SRL-{0000}</displayFormat>
        <label>Sales Receipt Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Receipt_Line_Item__c/fields/Item_Reference__c.field-meta.xml
<CustomField>
    <fullName>Item_Reference__c</fullName>
    <label>Item Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QboSubTotalLineItem.cls
public virtual class QboSubTotalLineItem {
    public static Sobject convert(Sales_Receipt_Line_Item__c lineItem , QboSubTotalLineDetail SubtotalLineDetail){
        lineItem.Item_Reference__c = SubtotalLineDetail?.ItemRef?.value;
        return lineItem;
    }

    public  static Sobject convert(Invoice_Line_Item__c lineItem , QboSubTotalLineDetail SubtotalLineDetail){
        lineItem.Item_Reference__c = SubtotalLineDetail?.ItemRef?.value;
        return lineItem;
    }



}