force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>LINE-{0000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Discount_Account_Reference__c.field-meta.xml
<CustomField>
    <fullName>Discount_Account_Reference__c</fullName>
    <label>Discount Account Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Tax_Code_Reference__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code_Reference__c</fullName>
    <label>Tax Code Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt_Line_Item__c/Sales_Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Receipt Line Item</label>
    <nameField>
        <displayFormat>SRL-{0000}</displayFormat>
        <label>Sales Receipt Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Receipt_Line_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <label>Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt_Line_Item__c/fields/Percent_Based__c.field-meta.xml
<CustomField>
    <fullName>Percent_Based__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Percent Based</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QboDiscountLineItem.cls
public virtual class QboDiscountLineItem {
        
    public static Sobject convert(Sales_Receipt_Line_Item__c lineItem , QboDiscountLineDetail DiscountLineDetail){
        lineItem.Tax_Code_Reference__c = DiscountLineDetail.TaxCodeRef.value;
        lineItem.Discount_Account_Reference__C = DiscountLineDetail.DiscountAccountRef.value;
        lineItem.Percent_Based__c = DiscountLineDetail.PercentBased;
        lineItem.Discount_Percent__c = DiscountLineDetail.DiscountPercent;
        return lineItem;
    }
   
        
    public static Sobject convert(Invoice_Line_Item__c lineItem , QboDiscountLineDetail DiscountLineDetail){
        lineItem.Tax_Code_Reference__c = DiscountLineDetail.TaxCodeRef.value;
        lineItem.Discount_Account_Reference__C = DiscountLineDetail.DiscountAccountRef.value;
        lineItem.Percent_Based__c = DiscountLineDetail.PercentBased;
        lineItem.Discount_Percent__c = DiscountLineDetail.DiscountPercent;
        return lineItem;
    }
    
    
    
}