force-app/main/default/objects/Qbo_Item__c/Qbo_Item__c.object-meta.xml
<CustomObject>
    <description>Represents an Item created in Quickbooks</description>
    <label>Qbo Item</label>
    <nameField>
        <label>Qbo Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qbo Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qbo_Item__c/fields/Abatement_Rate__c.field-meta.xml
<CustomField>
    <fullName>Abatement_Rate__c</fullName>
    <label>Abatement Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Asset_Account_Reference__c.field-meta.xml
<CustomField>
    <fullName>Asset_Account_Reference__c</fullName>
    <label>Asset Account Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Expense_Account_Ref__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account_Ref__c</fullName>
    <label>Expense Account Ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Fully_Qualified_Name__c.field-meta.xml
<CustomField>
    <fullName>Fully_Qualified_Name__c</fullName>
    <label>Fully Qualified Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Income_Account_Reference__c.field-meta.xml
<CustomField>
    <fullName>Income_Account_Reference__c</fullName>
    <label>Income Account Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Parent_Ref__c.field-meta.xml
<CustomField>
    <fullName>Parent_Ref__c</fullName>
    <label>Parent Ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Preferred_Vendor_Reference__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Vendor_Reference__c</fullName>
    <label>Preferred Vendor Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Purchase_Cost__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Cost__c</fullName>
    <label>Purchase Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Purchase_Description__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Description__c</fullName>
    <label>Purchase Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Purchase_Tax_Code_Reference__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Tax_Code_Reference__c</fullName>
    <label>Purchase Tax Code Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Qbo_Id__c.field-meta.xml
<CustomField>
    <fullName>Qbo_Id__c</fullName>
    <externalId>true</externalId>
    <label>Qbo Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Reorder_Point__c.field-meta.xml
<CustomField>
    <fullName>Reorder_Point__c</fullName>
    <label>Reorder Point</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Reverse_Charge_Rate__c.field-meta.xml
<CustomField>
    <fullName>Reverse_Charge_Rate__c</fullName>
    <label>Reverse Charge Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Sales_Tax_Code_Reference__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax_Code_Reference__c</fullName>
    <label>Sales Tax Code Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Sales_Tax_Included__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sales Tax Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Sku__c.field-meta.xml
<CustomField>
    <fullName>Sku__c</fullName>
    <label>Sku</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Sub_Item__c.field-meta.xml
<CustomField>
    <fullName>Sub_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sub Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Tax_Classification_Reference__c.field-meta.xml
<CustomField>
    <fullName>Tax_Classification_Reference__c</fullName>
    <label>Tax Classification Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/Track_Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Track_Qty_On_Hand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Qty On Hand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/UQC_Display_Text__c.field-meta.xml
<CustomField>
    <fullName>UQC_Display_Text__c</fullName>
    <label>UQC Display Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Qbo_Item__c/fields/UQC_Id__c.field-meta.xml
<CustomField>
    <fullName>UQC_Id__c</fullName>
    <label>UQC Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QboItem.cls
public virtual class QboItem extends QboDataObject implements IConvertible {
    
    public string ItemCategoryType {get;set;}
    public string Name {get;set;}
    public string Type {get;set;}
    public string Sku {get;set;}
    public string Source {get;set;}
    public string Description {get;set;}
    public string UQCDisplayText {get;set;}
    public string PurchaseDesc {get;set;}
    public string UQCId {get;set;}
    public string ServiceType {get;set;}
    public string FullyQualifiedName {get;set;}
    
    public Date InvStartDate {get;set;}
    
    public double QtyOnHand {get;set;}
    public double AbatementRate {get;set;}
    public double ReorderPoint {get;set;}
    public double ReverseChargeRate {get;set;}
    public double PurchaseCost {get;set;}
    public double UnitPrice {get;set;}
    public integer Level {get;set;}
    
    public boolean Active {get;set;}
    public boolean SalesTaxIncluded {get;set;}
    public boolean TrackQtyOnHand {get;set;}
    public boolean PurchaseTaxIncluded {get;set;}
    public boolean SubItem {get;set;}
    public boolean Taxable {get;set;}
    
    public QboDataObject.ReferenceType SalesTaxCodeRef {get;set;}
    public QboDataObject.ReferenceType AssetAccountRef {get;set;}
    public QBoDataObject.ReferenceType ClassRef {get;set;}
    public QboDataObject.ReferenceType PrefVendorRef {get;set;}
    public QboDataObject.ReferenceType PurchaseTaxCodeRef {get;set;}
    public QboDataObject.ReferenceType ParentRef {get;set;}
    public QboDataObject.ReferenceType ExpenseAccountRef {get;set;}
    public QboDataObject.ReferenceType IncomeAccountRef {get;set;}
    public QboDataObject.ReferenceType TaxClassificationRef {get;set;}
    
    
    
    public Sobject convert(){
        Qbo_Item__c item = (Qbo_Item__c)setDefaults(new Qbo_Item__c());
        item.Abatement_Rate__C = this.AbatementRate;
        item.Active__c = this.Active;
        item.Asset_Account_Reference__c = this.AssetAccountRef.value;
        item.Description__c = this.Description;
        item.Expense_Account_Ref__c = this.ExpenseAccountRef.value;
        item.Fully_Qualified_Name__c = this.FullyQualifiedName;
        item.Income_Account_Reference__c = this.IncomeAccountRef.value;
        item.Level__c = this.Level;
        item.Parent_Ref__c = this.ParentRef.value;
        item.Preferred_Vendor_Reference__c = this.PrefVendorRef.value;
        item.Purchase_Cost__c = this.PurchaseCost;
        item.Purchase_Description__c = this.PurchaseDesc;
        item.Purchase_Tax_Code_Reference__c = this.PurchaseTaxCodeRef.value;
        item.Purchase_Tax_Included__c = this.PurchaseTaxIncluded;
        item.Qbo_Id__c = this.Id;
        item.Quantity_On_Hand__c = this.QtyOnHand;
        item.Reorder_Point__c = this.ReorderPoint;
        item.Reverse_Charge_Rate__c = this.ReverseChargeRate;
        item.Sales_Tax_Code_Reference__c = this.SalesTaxCodeRef.value;
        item.Sales_Tax_Included__c = this.SalesTaxIncluded;
        item.Service_Type__c = this.ServiceType;
        item.Sku__c = this.Sku;
        item.Source__c = this.Source;
        item.Sub_Item__c = this.SubItem;
        item.Sync_Token__c = this.SyncToken;
        item.Tax_Classification_Reference__c = this.TaxClassificationRef.value;
        item.Taxable__c = this.Taxable;
        item.Track_Qty_On_Hand__c = this.TrackQtyOnHand;
        item.Unit_Price__c = this.UnitPrice;
        item.UQC_Display_Text__c = this.UQCDisplayText;
        item.UQC_Id__c = this.UQCId;
        return item;
    }

}