force-app/main/default/objects/Qb_Token__c/Qb_Token__c.object-meta.xml
<CustomObject>
    <description>Stores information for Quickbooks Tokens here</description>
    <label>Qb Token</label>
    <nameField>
        <displayFormat>QBT-{0000000000}</displayFormat>
        <label>Qb Token Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QbTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qb_Token__c/fields/Access_Code_Life_Span_Days__c.field-meta.xml
<CustomField>
    <fullName>Access_Code_Life_Span_Days__c</fullName>
    <description>Number of days our access code is valid for. Ideally should be 100 days</description>
    <label>Access Code Life Span (Days)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Qb_Token__c/fields/Auth_Token__c.field-meta.xml
<CustomField>
    <fullName>Auth_Token__c</fullName>
    <description>Access Token for requesting JWTs</description>
    <label>Auth Token</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qb_Token__c/fields/Last_Auth_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Auth_Date__c</fullName>
    <description>Last time we requested for authentication.</description>
    <label>Last Auth Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Qb_Token__c/fields/Realm_Id__c.field-meta.xml
<CustomField>
    <fullName>Realm_Id__c</fullName>
    <description>Realm Id for this token</description>
    <label>Realm Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qb_Token__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <description>Refresh Token</description>
    <label>Refresh Token</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qb_Token__c/fields/Refresh_Token_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token_Expiry__c</fullName>
    <label>Refresh Token Expiry</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QuickBooksOAuth2Handler.cls
/**
 * Handles the oAuth2 Flow by saving tokens in sf and automatically refreshing tokens
 * */
public class QuickBooksOAuth2Handler {
	
    public static PageReference ref;

    

    
    // maybe we can just modify this to authenticate once and for all (for first requests)
    // that way the qboauthhandler token always HAS a refresh token.
    public static void renewSession(map<string,string> params){
        QboLogger logger = QboLogger.getinstance();

        logger.log('renewing session');
        QB_Token__c mostRecent = new Qb_Token__c(Auth_Token__c = params.get('code') , Realm_Id__c = params.get('realmId'));
        Cache.OrgPartition localStorage = Cache.Org.getPartition('local.QboCache');
        // temporarily put these in cache !!! 
        localStorage.put('accesscode', params.get('code'));
        localStorage.put('realmId', params.get('realmId'));
        
        QboAuthHandler authHandler = QboAuthHandler.getInstance();
        if(authHandler.authenticate() == true){
            string refreshToken = (string)authHandler.getLastAuthResponseValueForKey('refresh_token');
            integer refreshTokenExpiry = (integer)authHandler.getLastAuthResponseValueForKey('x_refresh_token_expires_in');
            mostRecent.Last_Auth_Date__c = Datetime.now();
            mostRecent.Refresh_Token_Expiry__c = refreshTokenExpiry; 
            mostRecent.Refresh_Token__c = refreshToken;
            mostRecent.Access_Code_Life_Span_days__C = 101;
        }

        logger.log(Json.serialize(mostRecent));
        logger.close();
        insert mostRecent;
    }
    
    
    
    
    
    
    
}