force-app/main/default/objects/Qb_Token__c/Qb_Token__c.object-meta.xml
<CustomObject>
    <description>Stores information for Quickbooks Tokens here</description>
    <label>Qb Token</label>
    <nameField>
        <displayFormat>QBT-{0000000000}</displayFormat>
        <label>Qb Token Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QbTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qb_Token__c/fields/Jwt_Token_LifeSpan_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Jwt_Token_LifeSpan_Minutes__c</fullName>
    <description>How many minutes does our jwt token last</description>
    <label>Jwt Token LifeSpan Minutes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Qb_Token__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <description>Refresh Token</description>
    <label>Refresh Token</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QboUpdateToken_Queueable.cls
// we might never need to use this anymore !!!!
public with sharing class QboUpdateToken_Queueable implements Queueable , Schedulable{
    
    string tokenId;
    integer expiry;
    string refreshT;

    public QboUpdateToken_Queueable(string tokenId, integer jwtexpiry , string refreshtoken) {
        this.tokenId = tokenId;
        this.expiry = jwtexpiry;
        this.refreshT = refreshToken;
    }


    public void execute(System.SchedulableContext context){
        executeCommon(context.getTriggerId(),'sch');
    }
    public void execute(System.QueueableContext cont){
        executeCommon(cont.getJobId(),'que');
    }


    private void executeCommon(string jobId, string ctx){
        try{
            Qb_Token__c token = new Qb_Token__c();
            token.put('Id', tokenId);
            token.Refresh_Token__c = this.refreshT;
            token.Jwt_Token_LifeSpan_Minutes__c = this.expiry;
            upsert token;
            if(ctx.equalsIgnoreCase('sch')){
                System.abortJob(jobId);
            }
        }catch(Exception e){
            QboLogger logger = QboLogger.getinstance();
            logger.log(e);
            logger.close();
        }
    }

    
}