force-app/main/default/objects/Qb_Token__c/Qb_Token__c.object-meta.xml
<CustomObject>
    <description>Stores information for Quickbooks Tokens here</description>
    <label>Qb Token</label>
    <nameField>
        <displayFormat>QBT-{0000000000}</displayFormat>
        <label>Qb Token Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QbTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qb_Token__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <description>Refresh Token</description>
    <label>Refresh Token</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QBoAuthenticationRequest.cls
public class QBoAuthenticationRequest {
    
    public enum Mode {FRESH , REFRESH}
    
    private final http h = new Http();
    private Mode exMode;
    private final string endPoint;
    private string accessCode;
    private string realmId;
    private string redirectUrl;   
    private QboSettingsProvider settings = QBoSettingsProvider.getInstance();
    
    public class QBoAuthenticationResponse{
        public boolean success;
        private Map<string,Object> data;
        
        
        public QBoAUthenticationResponse(HttpResponse res){
            System.debug(res.getBody());
           	success = res.getStatusCode() == 200;
            data = (Map<string,Object>)Json.deserializeUntyped(res.getBody());
            
        }
        
        public Map<String,Object> get(){
            return data;
        }
        
    }
    
    public QboAuthenticationRequest(string accessCode, string realmId, string redirectUrl , Mode mode){
        endPoint = settings.getAccessTokenEndPoint();
        exMode = mode;
        this.accessCode = accessCode;
        this.realmId = realmId;
        this.redirectUrl = redirectUrl;
    }
    
    
    public string getRequestBody(){
        string res = '';
        System.debug('executing in mode ' + exMode.name());
        switch on exMode{
            when FRESH{
                res = 'grant_type=authorization_code&code=' + accessCode + '&redirect_uri=' + redirectUrl;
            }
            when REFRESH{
                QbObjectSelector selector = new QbObjectSelector('QB_Token__c');
                Qb_Token__c token = (QB_Token__c)selector.getMostRecent( QbObjectSelector.DbOp.CREATED,1)[0];
                string refreshToken = token.Refresh_Token__c; 
                res = 'grant_type=refresh_token&refresh_token=' + refreshToken;
            }
            when else{
                res ='';
            }
        }
        
        return res;
        
        
    }
    
    
    
    public QboAuthenticationResponse execute(){
        string authorization = settings.getAuthFromClientIdAndSecret(); 
        HttpRequest httpReq = new HttpRequest();
        HttpResponse httpRes = new HttpResponse();
        
        string requestBody = getRequestBody();
        
        httpReq.setMethod('POST');
        httpReq.setEndPoint(endPoint);
        httpReq.setHeader('Authorization', 'Basic ' + authorization);
        httpReq.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpReq.setBody(requestBody);
        
        
        return new QBoAuthenticationResponse(h.send(httpReq));
    }
    
    
    
    
    
    
    
}