force-app/main/default/objects/Qb_Token__c/Qb_Token__c.object-meta.xml
<CustomObject>
    <description>Stores information for Quickbooks Tokens here</description>
    <label>Qb Token</label>
    <nameField>
        <displayFormat>QBT-{0000000000}</displayFormat>
        <label>Qb Token Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QbTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qb_Token__c/fields/Last_Auth_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Auth_Date__c</fullName>
    <description>Last time we requested for authentication.</description>
    <label>Last Auth Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Qb_Token__c/fields/RefreshToken__c.field-meta.xml
<CustomField>
    <fullName>RefreshToken__c</fullName>
    <label>RefreshToken</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QboTokenDataObject.cls
public virtual class QboTokenDataObject extends QboDataObject implements IConvertible {

    public string refreshToken {get;set;}
    public Datetime lastAuthDate {get;set;}
    public integer refreshTokenExpiry {get;set;}


    public Sobject convert(){
        Qb_Token__c token = new Qb_Token__c();
        token.RefreshToken__c = this.refreshToken;
        token.Last_Auth_Date__c = this.lastAuthDate;
        return token;

    }
    
}