force-app/main/default/objects/QBO_Event__c/QBO_Event__c.object-meta.xml
<CustomObject>
    <description>Represents the QBO event notification</description>
    <label>QBO Event</label>
    <nameField>
        <displayFormat>QBE-{0000000000}</displayFormat>
        <label>QBO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QBO Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QBO_Event__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>What QBO entity did the event notification come in for</description>
    <label>Entity</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QBO_Event__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>What Operation occured for this event</description>
    <label>Operation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QBOEventProcessingNode.cls
public virtual class QBOEventProcessingNode extends IAsyncCollectionDsNode{

    public QBoEventProcessingNode(Qbo_Event__c data){
        this.data = data;
        this.dataType = Qbo_Event__c.class;
        
    }
    
    
    // use metadata provider to determine what to do
    // When Immediate : Make a Callout To retreive the data and kickstart callout Processing; 
    // system is already in an asynchronour context when this runs , so that leaves us with just one Queueable Job to run !!!!
    
    public override void execute(){
        QBo_Event__c event = (QBo_Event__c)data;
        QboDataSyncMetadaProvider meta = QboDataSyncMetadaProvider.getInstance(event.Entity__c);
        QboDataSyncMetadaProvider.Action eventAction = meta.getActionFromName(event.Operation__c.toLowerCase());
        QboLogger l = QboLogger.getinstance();
                
        if(eventAction != null && meta.getAllowedActions().contains(eventAction)){
            try{
                QBoAbstractActionHandler handler = QboActionHandlerFactory.getAction(eventAction);
                handler.execute(event);    
            }catch(Exception e){
               throw e;
            }
        }else{
            l.log(' An Invalid Action Unsubscribed action was invoked');
        }
        
    }
    
    
    
}