force-app/main/default/objects/QBO_Event__c/QBO_Event__c.object-meta.xml
<CustomObject>
    <description>Represents the QBO event notification</description>
    <label>QBO Event</label>
    <nameField>
        <displayFormat>QBE-{0000000000}</displayFormat>
        <label>QBO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QBO Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QBO_Event__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>What QBO entity did the event notification come in for</description>
    <label>Entity</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QBO_Event__c/fields/Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Entity_Id__c</fullName>
    <description>The Id of the entity from QBO</description>
    <label>Entity Id</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QboDeletedActionHandler.cls
public virtual class QboDeletedActionHandler extends QboAbstractActionHandler {
    
    public override void execute(Qbo_Event__c event){
        string qboId = event.Entity_Id__c;
        string entity = event.Entity__c;

        QboDataSyncMetadaProvider metadataProvider = QboDataSyncMetadaProvider.getInstance(entity);
        string sobjectType = metadataProvider.getSobjectType();
        string query = 'Select Id From ' +sobjectType + ' WHERE Qbo_Id__c =\''+qboId+'\'';
        Sobject record = Database.query(query)[0];

        Database.delete(record);
        
    }

}