force-app/main/default/objects/QBO_Event__c/QBO_Event__c.object-meta.xml
<CustomObject>
    <description>Represents the QBO event notification</description>
    <label>QBO Event</label>
    <nameField>
        <displayFormat>QBE-{0000000000}</displayFormat>
        <label>QBO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QBO Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QBO_Event__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>What QBO entity did the event notification come in for</description>
    <label>Entity</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QBO_Event__c/fields/Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Entity_Id__c</fullName>
    <description>The Id of the entity from QBO</description>
    <label>Entity Id</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QBO_Event__c/fields/Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Last_Updated__c</fullName>
    <description>When the change was made to the event entity</description>
    <label>Last Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QBO_Event__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>What Operation occured for this event</description>
    <label>Operation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QBOEventParser.cls
public virtual class QBOEventParser {
	
    private final string objectType = 'QBO_Event__c';
        
    public class QBOEvent{
        public List<QBOEventNotification> eventNotifications {get;set;}
        
        public void save(){
            List<QboDataChangeEventEntity> eventEntities = new List<QboDataChangeEventEntity>();
            List<Qbo_Event__c> eventRecords = new List<Qbo_Event__c>();
            if(eventNotifications != null && eventNotifications.size() > 0){
                for(QboEventNotification notf : eventNotifications){
                    eventEntities.addAll(notf.dataChangeEvent.entities);
                }
            }
            
            if(eventEntities.size() > 0){
                
                for(QboDataChangeEventEntity entity : eventEntities){
                    eventRecords.add(entity.get());
                }
                
                insert eventRecords;
            }
            
            
            
        }
    }
    
    public class QBOEventNotification{
        public string realmId {get;set;}
        public QboDataChangeEvent dataChangeEvent {get;set;}
        
    }
    
    public class QboDataChangeEventEntity{
        public string name {get;set;}
        public string id {get;set;}
        public string operation {get;set;}
        public DateTime lastUpdated {get;set;}
        
        public Qbo_Event__c get(){
            return new Qbo_Event__c(Entity__c = name , Entity_Id__c = Id , Operation__c = operation , Last_Updated__c = lastUpdated);
        }
    }
    
    public class QboDataChangeEvent{
        public list<QboDataChangeEventEntity> entities;
    }
    
    public static void parse(string eventJson){
        QBOEvent event = (QBOEvent)Json.deserialize(eventJson, QBOEvent.class);
        event.save();
    }
    
    
    
}