force-app/main/default/objects/Sales_Receipt__c/Sales_Receipt__c.object-meta.xml
<CustomObject>
    <label>Sales Receipt</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Receipt__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>Value set by default from QB. Any value populated manually will be overwritten by value from QB</description>
    <inlineHelpText>Value set by default from QB. Any value populated manually will be overwritten by value from QB</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Bill_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_Address__c</fullName>
    <label>Bill Address</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Bill_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_Email_Address__c</fullName>
    <label>Bill Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Currency_Ref__c.field-meta.xml
<CustomField>
    <fullName>Currency_Ref__c</fullName>
    <label>Currency Ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Customer_Ref__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ref__c</fullName>
    <label>Customer Ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Doc_Number__c.field-meta.xml
<CustomField>
    <fullName>Doc_Number__c</fullName>
    <label>Doc Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Free_Form_Address__c.field-meta.xml
<CustomField>
    <fullName>Free_Form_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Free Form Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Global_Tax_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Global_Tax_Calculation__c</fullName>
    <label>Global Tax Calculation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Home_Balance__c.field-meta.xml
<CustomField>
    <fullName>Home_Balance__c</fullName>
    <label>Home Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Home_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Home_Total_Amount__c</fullName>
    <label>Home Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Payment_Ref_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Ref_Number__c</fullName>
    <label>Payment Ref Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Private_Notes__c.field-meta.xml
<CustomField>
    <fullName>Private_Notes__c</fullName>
    <label>Private Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Ship_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_Address__c</fullName>
    <label>Ship Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Ship_From_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Address__c</fullName>
    <label>Ship From Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Sync_Token__c.field-meta.xml
<CustomField>
    <fullName>Sync_Token__c</fullName>
    <label>Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Total_Amt__c.field-meta.xml
<CustomField>
    <fullName>Total_Amt__c</fullName>
    <label>Total Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Total_tax__c.field-meta.xml
<CustomField>
    <fullName>Total_tax__c</fullName>
    <label>Total tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Receipt__c/fields/Txn_Date__c.field-meta.xml
<CustomField>
    <fullName>Txn_Date__c</fullName>
    <label>Txn Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/QboSalesReceipt.cls
public class QboSalesReceipt extends QboAbstractDataChildObject implements IConvertible, IChildrenable {
    
    public List<QboSalesLine> Line {get;set;}
    
    public QboDataObject.EmailAddress BillEmailCc {get;set;}
    public QboDataObject.EmailAddress BillEmail {get;set;}
    public QboDataObject.EmailAddress BillEmailBcc {get;set;}
    
    public QbodataObject.TxnTaxDetail TxnTaxDetail {get;set;}
    public QboDataObject.CreditCardPayment CreditCardPayment {get;set;}
    
    
    public Date TxnDate {get;set;}
    public Date DueDate {get;set;}
    public Date ShipDate {get;set;}
    
    
    public QboDataObject.ReferenceType ClassRef {get;set;}
    public QboDataObject.ReferenceType CustomerRef {get;set;}
    public QboDataObject.ReferenceType CurrencyRef {get;set;}
    public QBoDataObject.ReferenceType DepositToAccountRef {get;set;}
    public QboDataObject.ReferenceType SalesTermRef {get;set;}
    public QboDataObject.ReferenceType ShipMethodRef {get;set;}
    public QboDataObject.ReferenceType RecurDataRef {get;set;}
    public QBoDataObject.ReferenceType DepartmentRef {get;set;}
   
    
    public string TrackingNum {get;set;}
    public string PrintStatus {get;set;}
    public string DocNumber {get;set;}
    public string TxnSource {get;set;}
    public string GlobalTaxCalculation {get;set;}
    public string TransactionLocationType {get;set;}
    public string PrivateNote {get;set;}
    public string PaymentRefNum {get;set;}
    public string EmailStatus {get;set;}
    public string salesReceiptLink {get;set;}
    
    
    public boolean FreeFormAddress {get;set;}
    public boolean AllowOnlineACHPayment {get;set;}
    public boolean AllowOnlineCreditCardPayment {get;set;}
    public boolean ApplyTaxAfterDiscount {get;set;}
    
    public double ExchangeRate {get;set;}
    public double Deposit {get;set;}
    public double TotalAmt {get;set;}
    public double HomeTotalAmt {get;set;}
    public double Balance {get;set;}
    public double HomeBalance {get;set;}
    public double Amount {get;set;}
    public double TotalTax {get;set;}
    
    public QboDataObject.PhysicalAddress BillAddr {get;set;}
    public QboDataObject.PhysicalAddress ShipAddr {get;set;}
    public QboDataObject.PhysicalAddress ShipFromAddr {get;set;}


    
    public  override Schema.SObjectType getSobjectType(){
        return Sales_Receipt__c.getSobjectType();
    }
    
    
    
    
    
    
    
    public Sobject convert(){
        Sales_Receipt__c salesReceipt  = (Sales_Receipt__c)setDefaults(new Sales_Receipt__c());
        salesReceipt.Qbo_id__c = this.Id;
        salesReceipt.Customer_Ref__c = this.CustomerRef.value;
        salesReceipt.Doc_Number__c = this.DocNumber;
        salesReceipt.Sync_Token__c = this.SyncToken;
        salesReceipt.Currency_Ref__c = this.CurrencyRef.value;
        salesReceipt.Bill_Email_Address__c = this.BillEmail.Address;
        salesReceipt.Txn_Date__c = this.TxnDate;
        salesReceipt.Ship_From_Address__c = this.ShipFromAddr.toString();
        salesReceipt.Ship_Address__c = this.ShipAddr.toString();
        salesReceipt.Amount__c = this.Amount;
        salesReceipt.Ship_Date__c = this.ShipDate;
        salesReceipt.Tracking_Number__c = this.TrackingNum;
        salesReceipt.Payment_Ref_Number__c = this.PaymentRefNum;
        salesReceipt.Global_Tax_Calculation__c = this.GlobalTaxCalculation;
        salesReceipt.Apply_Tax_After_Discount__c = this.ApplyTaxAfterDiscount;
        salesReceipt.Private_Notes__c = this.PrivateNote;
        salesReceipt.Total_Tax__c = this.TotalTax;
        salesReceipt.Bill_Address__c = this.BillAddr.toString();
        salesReceipt.Home_Balance__c = this.HomeBalance;
        salesReceipt.Total_Amt__c = this.TotalAmt;
        salesReceipt.Balance__c = this.Balance;
        salesReceipt.Home_Total_Amount__c = this.HomeTotalAmt;
        salesReceipt.Free_Form_Address__c = this.FreeFormAddress;

        return (Sales_Receipt__c)this.relateToParent(salesReceipt);
    }

    
    public List<QboDataObject> getChildren(){
        List<QboDataObject> children = new List<QboDataObject>();
        children.addAll(this.Line);
        return children;
        
    }
    
}