force-app/main/default/objects/QuickBooks_Connection_Settings__c/QuickBooks_Connection_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores the custom settings for the  QuickBooks Online Integration</description>
    <label>QuickBooks Connection Settings</label>
</CustomObject>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Callback_Url__c.field-meta.xml
<CustomField>
    <fullName>Callback_Url__c</fullName>
    <description>Registers the callback url</description>
    <label>Callback Url</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>Sandbox Client Id</description>
    <label>Client Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>The client Secret</description>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Is_QuickBooks_Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Is_QuickBooks_Sandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are we connecting to a QuickBooks Sandbox</description>
    <label>Is QuickBooks Sandbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Prod_Minor_Version__c.field-meta.xml
<CustomField>
    <fullName>Prod_Minor_Version__c</fullName>
    <description>Production minor api version</description>
    <label>Prod Minor Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Production_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Production_Base_Url__c</fullName>
    <description>Production Base Url</description>
    <label>Production Base Url</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Production_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Production_Company_Id__c</fullName>
    <description>Production Company Id</description>
    <label>Production Company Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Qbo_Auth_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Qbo_Auth_Endpoint__c</fullName>
    <description>Endpoint to request authorization code</description>
    <label>Qbo Auth Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Qbo_FetchAccessToken_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Qbo_FetchAccessToken_EndPoint__c</fullName>
    <description>use this to fetch an access token</description>
    <label>Qbo FetchAccessToken EndPoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Sandbox_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Base_Url__c</fullName>
    <description>Base Url for QB Sandbox</description>
    <label>Sandbox Base Url</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Sandbox_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Company_Id__c</fullName>
    <description>Sandbox Company Id</description>
    <label>Sandbox Company Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickBooks_Connection_Settings__c/fields/Sandbox_Minor_Version__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Minor_Version__c</fullName>
    <description>minor api version</description>
    <label>Sandbox Minor Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QboSettingsProvider.cls
public class QboSettingsProvider {

    public class NoSettingsFoundException extends Exception{}
    
    private static QboSettingsProvider instance;
    
    public static QboSettingsProvider getInstance(){
        if(instance == null) instance = new QboSettingsProvider();
        return instance;
    }
    
    private QuickBooks_Connection_Settings__c settingsRecord;
    private boolean canUse;
    
    private QboSettingsProvider(){
        settingsRecord = QuickBooks_Connection_Settings__c.getOrgDefaults();
        if(settingsRecord == null){
            throw new QboSettingsProvider.NoSettingsFoundException('Could not Find a default organizational record for QuickBooks_Connection_Settings__c. Please create one and try again');
        }
        canUse = settingsRecord != null;
    }
    
    
    public string getAuthenticationBaseUrl(){
        string res ='';
        if(canUse){
        	string authEndP = settingsRecord.Qbo_Auth_Endpoint__c.endsWithIgnoreCase('/') ? settingsRecord.Qbo_Auth_Endpoint__c : settingsRecord.Qbo_Auth_Endpoint__c+'/';
            res= authEndP;
        }
       return res;
    }
    
    public string getAccessTokenEndPoint(){
         string res ='';
        if(canUse){
        	res = settingsRecord.Qbo_FetchAccessToken_EndPoint__c;
        }
       return res;
    }
    
     public string getCallBackUrl(){
         string res ='';
        if(canUse){
        	res = settingsRecord.Callback_Url__c;
        }
       return res;
    }
    
    
    public string getFullOAuthUrl(string scopes, string redirecturi){
        string res ='';
        if(canUse){
         	string authEndP = settingsRecord.Qbo_Auth_Endpoint__c.endsWithIgnoreCase('/') ? settingsRecord.Qbo_Auth_Endpoint__c : settingsRecord.Qbo_Auth_Endpoint__c+'/';   
        	res = authEndP + '?client_id='+settingsRecord.Client_Id__c+'&response_type=code&scope='+scopes+'&state=123445633443&redirect_uri='+redirecturi;
        }
        return res;
    }
    
    // get authorization code
    public string getAuthFromClientIdAndSecret(){
        string res ='';
        if(canUse){
        	string clientId = settingsRecord.Client_Id__c;
        	string clientSecret = settingsRecord.Client_Secret__c;
            res = EncodingUtil.base64Encode(Blob.valueOf(clientId +':'+clientSecret));
        }
        
        return res;
    }
    
    public string getApiBaseUrl(){
        string res ='';
        if(canUse){
            res = settingsRecord.Is_QuickBooks_Sandbox__c ? settingsRecord.Sandbox_Base_Url__c : settingsRecord.Production_Base_Url__c;
        }
        return res;
    }

    public string getMinorVersionParam(){
        string res ='?minorversion=';
        if(canUse){
			res+= settingsRecord.Is_QuickBooks_Sandbox__c ? settingsRecord.Sandbox_Minor_Version__c : settingsRecord.Prod_Minor_Version__c;
        }
        
        return res;
    }
    public string getCompanyId(){
        string res = '';
        if(canUse){
            res+= settingsRecord.Is_QuickBooks_Sandbox__c ? settingsRecord.Sandbox_Company_Id__c : settingsRecord.Production_Company_Id__c;
        }
    	return res;
    }
    
    public string getFullApiUrlTemplate(){
        return getApiBaseUrl() +'/v3/company/'+ getCompanyId() +'/{0}'+ getMinorVersionParam();
        
    }    
    
    
    
    
    
}