force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Represents a Log Object</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Dumps__c.field-meta.xml
<CustomField>
    <fullName>Dumps__c</fullName>
    <description>Data Dump</description>
    <label>Dumps</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QboLogger.cls
public virtual without sharing class QboLogger {
    
    private static QboLogger instance;
    

    public static QboLogger getinstance(){
        if(instance == null){
            instance = new QboLogger();
        }
        return instance;
    }
    
    
    private List<Log__c> logs;
    private boolean commitImmediately;
    private integer autoCommitSize;
    
    private QboLogger() {
        logs = new List<Log__c>();
        commitImmediately = false;
        autoCommitSize = 10;
    }
    

    public void toggleCommitImmediately(boolean commitImmediately) {
        this.commitImmediately = commitImmediately;
    }

    public void setAutoCommitSize(integer autoCommitSize) {
        this.autoCommitSize = autoCommitSize;
    }


    public QboLogger log(Exception e){
        Log__c l = new Log__c();
        string dumps = 'Exception At : ' +e.getStackTraceString() +'\n' +'Message : '+ e.getMessage();
        l.Dumps__c = dumps;
        logs.add(l);
        write();
        return this;
    }

    public QboLogger log(string raw){
        Log__c log = new Log__c();
        log.dumps__c = raw;
        logs.add(log);
        write();
        return this;
    }



    private void write(){
        if(commitImmediately == true || logs.size() == autoCommitSize){
            insert logs;
            logs = new List<Log__c>();
        }
    }

    public void close(){
        this.toggleCommitImmediately(true);
        write();
    }

    
}