force-app/main/default/objects/Invoice__c/fields/Allow_Online_Ach_Payment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Online_Ach_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Online Ach Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Allow_Online_Credit_Card_Payment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Online_Credit_Card_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Online Credit Card Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Apply_Tax_After_Discount__c.field-meta.xml
<CustomField>
    <fullName>Apply_Tax_After_Discount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apply Tax After Discount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>Invoice balance</description>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Currency_Ref__c.field-meta.xml
<CustomField>
    <fullName>Currency_Ref__c</fullName>
    <label>Currency Ref</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <description>invoice deposit</description>
    <label>Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Doc_Number__c.field-meta.xml
<CustomField>
    <fullName>Doc_Number__c</fullName>
    <label>Doc Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <label>Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotSet</fullName>
            </value>
            <value>
                <fullName>NeedToSend</fullName>
            </value>
            <value>
                <fullName>EmailSent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/FreeForm_Address__c.field-meta.xml
<CustomField>
    <fullName>FreeForm_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FreeForm Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Link__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Link__c</fullName>
    <label>Invoice Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Message_On_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Message_On_Invoice__c</fullName>
    <label>Message On Invoice</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/QB_Customer_Ref__c.field-meta.xml
<CustomField>
    <fullName>QB_Customer_Ref__c</fullName>
    <label>QB Customer Ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/QB_Email__c.field-meta.xml
<CustomField>
    <fullName>QB_Email__c</fullName>
    <label>QB Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Transaction_Source__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Source__c</fullName>
    <label>Transaction Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QboInvoice.cls
public virtual class QboInvoice extends QboAbstractDataChildObject implements IConvertible, IChildrenable{
    
    public List<QboInvoiceLine> Line {get;set;}
    
    public QboDataObject.EmailAddress BillEmail {get;set;}
    public QboDataObject.EmailAddress BillEmailCc {get;set;}
    public QboDataObject.EmailAddress BillEmailBcc {get;set;}
    
    public Date TxnDate {get;set;}
    public Date ShipDate {get;set;}
    public Date DueDate {get;set;}
    
    public QboDataObject.PhysicalAddress BillAddr {get;set;}
    public QboDataObject.PhysicalAddress ShipFromAddr {get;set;}
    
    
    public string DocNumber {get;set;}
    public string TrackingNum {get;set;}
    public string PrintStatus {get;set;}
    public string TxnSource {get;set;}
    public string GlobalTaxCalculation {get;set;}
    public string TransactionLocationType {get;set;}
    public string PrivateNote {get;set;}
    public string EmailStatus {get;set;}
    public string InvoiceLink {get;set;}
    
    public QboDataObject.ReferenceType ClassRef {get;set;}
    public QboDataObject.ReferenceType CustomerRef {get;set;}
    public QboDataObject.ReferenceType SalesTermRef {get;set;}
    public QBoDataObject.ReferenceType DepartmentRef {get;set;}
    public QBoDataObject.ReferenceType ShipMethodRef {get;set;}
    
    public boolean AllowOnlineACHPayment {get;set;}
    public boolean AllowOnlineCreditCardPayment {get;set;}
    public boolean ApplyTaxAfterDiscount {get;set;}
    public boolean FreeFormAddress {get;set;}
    

    public decimal ExchangeRate {get;set;}
    public decimal Deposit {get;set;}
    public decimal HomeBalance {get;set;}
    public long TotalAmt {get;set;}
    public decimal HomeTotalAmt {get;set;}
    public decimal Balance {get;set;}


    public  override Schema.SObjectType getSobjectType(){
        return Invoice__c.getSobjectType();
    }
    
    
    
    
    
    
    
    public Sobject convert(){
        Invoice__c invoice  = (Invoice__c)setDefaults(new Invoice__c());
        invoice.Invoice_Due_Date__c = this.DueDate;
        invoice.Message_on_Invoice__c = this.PrivateNote;
        invoice.Qb_Email__c = this.BillEmail.Address;
        invoice.Allow_Online_Ach_Payment__c = this.AllowOnlineACHPayment;
        invoice.Allow_Online_Credit_Card_Payment__c = this.AllowOnlineCreditCardPayment;
        invoice.Apply_Tax_After_Discount__c = this.ApplyTaxAfterDiscount;
        invoice.Balance__c = this.Balance;
        invoice.Currency_Ref__c = this.CustomerRef.value;
        invoice.Deposit__c = this.Deposit;
        invoice.Email_Status__c = this.EmailStatus;
        invoice.Home_Total_Amount__c = this.HomeTotalAmt;
        invoice.Total_Amount__c = this.TotalAmt;
        invoice.Tracking_Number__c = this.TrackingNum;
        invoice.Transaction_Date__c = this.TxnDate;
        invoice.Transaction_Source__c = this.TxnSource;
        invoice.Qb_Customer_Ref__c = this.CustomerRef.value;
        invoice.Doc_Number__c = this.DocNumber;
        invoice.Invoice_Link__c = this.InvoiceLink;
        invoice.FreeForm_Address__c = this.FreeFormAddress;
        
        return (Invoice__c)this.relateToParent(invoice);
    }

    
    public List<QboDataObject> getChildren(){
        List<QboDataObject> children = new List<QboDataObject>();
        children.addAll(this.Line);
        return children;
        
    }
    
}