force-app/main/default/objects/Qbo_DataSync_Options__mdt/Qbo_DataSync_Options__mdt.object-meta.xml
<CustomObject>
    <description>Metadata containing options for syncing data from SF to QB</description>
    <label>Qbo DataSync Options</label>
    <pluralLabel>Qbo DataSync Options</pluralLabel>
</CustomObject>

force-app/main/default/objects/Qbo_DataSync_Options__mdt/fields/Qbo_Entity__c.field-meta.xml
<CustomField>
    <fullName>Qbo_Entity__c</fullName>
    <description>The qbo entity of interest</description>
    <label>Qbo Entity</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Qbo_DataSync_Options__mdt/fields/Sobject_Type__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Type__c</fullName>
    <description>The Sobject type for which this event gets transformed</description>
    <label>Sobject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qbo_DataSync_Options__mdt/fields/Subscribe_To_Create_Event__c.field-meta.xml
<CustomField>
    <fullName>Subscribe_To_Create_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permits actions after we receive a create event fromm qbo</description>
    <label>Subscribe To Create Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Qbo_DataSync_Options__mdt/fields/Subscribe_To_Delete_Event__c.field-meta.xml
<CustomField>
    <fullName>Subscribe_To_Delete_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permits Delete actions after event is received from Qbo</description>
    <label>Subscribe To Delete Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Qbo_DataSync_Options__mdt/fields/Subscribe_To_Update_Event__c.field-meta.xml
<CustomField>
    <fullName>Subscribe_To_Update_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permit update actions</description>
    <label>Subscribe To Update Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QboDataSyncMetadaProvider.cls
/**
 * @description : provides a uniform interface to retreive metadata for integration operations
 * */
public class QboDataSyncMetadaProvider {

    
    
    public enum Action {CREATED , UPDATED , DELETED}
   
    private map<string,Action> qboActions = new Map<string,Action>{'create'=>Action.CREATED, 'update'=>Action.UPDATED , 'delete'=>Action.DELETED};
        
   
    
    private static QboDataSyncMetadaProvider instance;
    
    private string ofType;
    
    private Qbo_DataSync_Options__mdt options;
    
    
    
    public boolean equals(string dType){
        return ofType.equalsIgnoreCase(dType);
        
    }
    
    
    public Action getActionFromName(string actionAlias){
        return qboActions.get(actionAlias);
    }
    
    public static QBoDataSyncMetadaProvider getInstance(string dtype){
        if(instance == null || !instance.equals(dtype)){
            instance = new QbodataSyncMetadaProvider(dType);
        }
        return instance;
    }
    
    
    private QBoDataSyncMetadaprovider(string stype){
        this.ofType = sType;
        List<Sobject> sobjects = new List<Sobject>();
        string allFieldQuery = new QbobjectSelector('Qbo_DataSync_Options__mdt').allFieldQuery();
        allFieldquery += ' Where Qbo_Entity__c = \'' + stype + '\'';
        sobjects = Database.query(allFieldquery);
        if(sobjects != null && sobjects.size() > 0){
            options = (Qbo_DataSync_Options__mdt)sobjects[0];
        }
    }
    
    public List<Action> getAllowedActions(){
        List<Action> actions = new List<Action>();
        
        if(options.Subscribe_To_Create_event__c){
            actions.add(Action.CREATED);
        }
        if(options.Subscribe_To_Update_Event__c){
            actions.add(Action.UPDATED);
        }
        
        if(options.Subscribe_To_Delete_Event__c){
            actions.add(Action.DELETED);
        }
        
        return actions;
        
    }


    public string getSobjectType(){
        return options.Sobject_Type__c;
    }
    
    
    
    
    
   
    
    
    
    
    
}